# Generated by Django 5.0.4 on 2024-06-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0002_rename_adhar_card_laborregistration_addhar_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('party_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255, unique=True)),
                ('party_email', models.EmailField(max_length=255, unique=True)),
                ('party_mobile', models.CharField(max_length=255)),
                ('party_address', models.CharField(max_length=255)),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.laborregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
