# Generated by Django 5.0.4 on 2024-06-27 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0003_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField()),
                ('task_start_date', models.DateField()),
                ('task_end_date', models.DateField()),
                ('task_status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('paused', 'Paused'), ('waiting', 'Waiting')], default='waiting', max_length=255)),
                ('task_total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.laborregistration')),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.party')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
