# Generated by Django 5.0.4 on 2024-07-03 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='task_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('partial', 'Partial')], default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='task_remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TaskPayment',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('task_payment_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('proof', models.ImageField(upload_to='')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
