# Generated by Django 5.0.4 on 2024-06-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborregistration',
            old_name='adhar_card',
            new_name='addhar_card',
        ),
        migrations.AddField(
            model_name='laborregistration',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='laborregistration',
            name='otp',
            field=models.CharField(blank=True, default='111111', max_length=10),
        ),
    ]
