# Generated by Django 5.0.4 on 2024-07-05 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0005_task_task_paid_amount_task_task_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ImageField(default='', upload_to='')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labor.laborregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
