# Generated by Django 5.0.4 on 2024-07-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0006_laborprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborprofile',
            name='profile',
            field=models.ImageField(default='default_images/default_user.jpg', upload_to=''),
        ),
    ]
