# Generated by Django 5.0.4 on 2024-07-08 04:50

import master.utils.WB_UNIQUE.create_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0007_alter_laborprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpayment',
            name='proof',
            field=models.ImageField(upload_to=master.utils.WB_UNIQUE.create_filename.generate_filename),
        ),
    ]
