# Generated by Django 5.0.4 on 2024-07-08 04:53

import master.utils.WB_UNIQUE.create_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0008_alter_taskpayment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborprofile',
            name='profile',
            field=models.ImageField(default='default_images/default_user.jpg', upload_to=master.utils.WB_UNIQUE.create_filename.generate_filename),
        ),
    ]
