# Generated by Django 5.0.4 on 2024-07-08 05:40

import master.utils.WB_UNIQUE.create_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0009_alter_laborprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborprofile',
            name='profile',
            field=models.ImageField(default='default_images/labor_profile_images.jpg', upload_to=master.utils.WB_UNIQUE.create_filename.generate_filename),
        ),
    ]
